spring:
  application:
    name: ec2-test-app

  datasource:
    #url: jdbc:mysql://localhost:3306/ec2_testdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #RDS 인스턴스 엔드포인트
    url: jdbc:mysql://ec2-test-db.clcoio4awcwd.ap-northeast-2.rds.amazonaws.com:3306/ec2testdb
    username: admin #RDS 마스터 사용자 이름
    password: 12345678  #RDS 마스터 암호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #기존 테이블 유지하고 변경사항만 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true  #SQL 쿼리 포맷팅해서 출력 (읽기 쉽게)
        dialect: org.hibernate.dialect.MySQLDialect #MySQL 방언 설정
        
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.example.ec2testapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "$d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080